name: brick_breaker
description: "Brick Breaker Game Made With The Dart Language And Flutter Framework"
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flame: ^1.16.0
  flutter:
    sdk: flutter

  flutter_soloud: ^2.0.0
  flame_audio: ^2.10.2
  logging: ^1.2.0
  
  flutter_animate: ^4.5.0
  google_fonts: ^6.1.0
  
  ffi: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/music/looped-song.ogg
    - assets/sounds/pew1.mp3
    - assets/sounds/pew2.mp3
    - assets/sounds/pew3.mp3